DROP TABLE access_rights;
DROP TABLE group_packs;
DROP TABLE rights;
DROP TABLE user_cards;
DROP TABLE user_groups;
DROP TABLE user_packs;
DROP TABLE cards;
DROP TABLE packs;
DROP TABLE groups;
DROP TABLE users;

DROP TYPE GEN_GOAL_TYPE;
DROP TYPE NOTIFICATION_TYPE;
DROP TYPE PRIVACY_TYPE;
DROP TYPE CARD_STATUS_TYPE;
DROP TYPE RIGHTS_TYPE;
DROP TYPE INVITATION_TYPE;
DROP TYPE CARD_TYPE;
